site_name: Breadboard Mates Resources
site_url: https://resources.breadboardmates.com/
nav:
  - Home: index.md
  - Manuals:
    - Mates Studio: 
      - Mates Studio/index.md
      - Graphics Editor: Mates Studio/mates-studio-graphics-editor.md
      - Code Editor: Mates Studio/mates-studio-code-editor.md
      - Blocks Editor: Mates Studio/mates-studio-blocks-editor.md
      - Controller Interface: Mates Studio/mates-controller-interface.md
      - Command Protocol: Mates Studio/mates-controller-command-protocol.md
    - Mates Controller Libraries:
      - Arduino: controller/arduino-mates-controller.md
      - Python: controller/python-mates-controller.md
  - Products:
    - TIMI:
      - TIMI-96: products/timi/timi-96-datasheet.md
      - TIMI-130: products/timi/timi-130-datasheet.md
      - TIMI-MB: products/timi/timi-mb-datasheet.md
    - TED:
      - TED-96: products/ted/ted-96-datasheet.md
      - TED-130: products/ted/ted-130-datasheet.md
    - REPTOR:
      - REPTOR-250: products/reptor/reptor-250-datasheet.md
    - Accessories:
      - Mates Programmer: products/accessories/bbm-programmer-datasheet.md
      - Pi Adaptor: products/accessories/bbm-pi-adaptor-datasheet.md
      - MB Adaptor: products/accessories/bbm-mb-adaptor-datasheet.md
      - Wind Adaptor: products/accessories/bbm-wing-adaptor-datasheet.md
    - MatesBUS: products/matesbus-datasheet.md
  - Tutorials:
    - Commander:
      - tutorials/commander/index.md
      - Tutorial No.1: tutorials/commander/tutorial-1.md
    - Architect:
      - tutorials/architect/index.md
      - Tutorial No.1: tutorials/architect/tutorial-1.md
    - Genius:
      - tutorials/genius/index.md
      - Tutorial No.1: tutorials/genius/tutorial-1.md
    - Builder:
      - tutorials/builder/index.md
      - Tutorial No.1: tutorials/builder/tutorial-1.md
  - Projects:
    - Standalone:
      - Pacman: projects/standalone/reptor-pacman.md
    - Arduino:
      - RGB Controller: projects/arduino/reptor-rgb-controller.md
extra_css:
    - css/custom.css
theme:
  name: material
  logo: full-logo.svg
  favicon: logo.svg
  extra:
    homepage: https://www.breadboardmates.com
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: 'indigo'
      accent: 'deep orange'
      toggle:
        icon: material/weather-night
        name: Switch to Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'deep orange'
      accent: 'indigo'
      toggle:
        icon: material/weather-sunny
        name: Switch to Light Mode
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
    - search
    - pdf-export
    