site_name: Breadboard Mates Resources
site_url: https://resources.breadboardmates.com/
nav:
  - Home: README.md
  - Docs: docs.md
  - Mates Studio: 
    - Setup: studio/manual.md
    - Commander: studio/commander.md
    - Architect: studio/architect.md
    - Genius: studio/genius.md
    - Builder: studio/builder.md
  - Mates Controller Libraries:
    - Arduino: controller/arduino.md
    - Python: controller/python.md
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: 'indigo'
      accent: 'deep orange'
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'deep orange'
      accent: 'indigo'
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
    - search
    - pdf-export
    