site_name: Breadboard Mates Resources
site_url: https://resources.breadboardmates.com/
nav:
  - Home: index.md
  - Manuals:
    - Mates Studio: 
      - studio/mates-studio-user-manual.md
      - Graphics Editor: studio/mates-studio-graphics-editor.md
      - Code Editor: studio/mates-studio-code-editor.md
      - Blocks Editor: studio/mates-studio-blocks-editor.md
      - Controller Interface: studio/mates-controller-interface.md
      - Command Protocol: studio/mates-controller-command-protocol.md
      - Release Notes: studio/mates-studio-release-notes.md
    - Mates Controller Libraries:
      - Arduino: controller/arduino-mates-controller.md
      - Python: controller/python-mates-controller.md
  - Projects:
    - Standalone:
      - Pacman: projects/standalone/reptor-pacman.md
    - Arduino:
      - RGB Controller: projects/arduino/reptor-rgb-controller.md
  - Tutorials:
    - Commander:
      - Getting Started: tutorials/commander/commander-getting-started.md
    - Architect:
      - Getting Started: tutorials/architect/architect-getting-started.md
    - Genius:
      - Getting Started: tutorials/genius/genius-getting-started.md
    - Builder:
      - Getting Started: tutorials/builder/builder-getting-started.md
extra_css:
    - css/custom.css
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: 'indigo'
      accent: 'deep orange'
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'deep orange'
      accent: 'indigo'
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
    - search
    - pdf-export
    