site_name: Markdown Docs Sample
site_url: https://example.com/
nav:
  - Home: README.md
  - Docs: docs.md
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: 'indigo'
      accent: 'deep orange'
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'deep orange'
      accent: 'indigo'
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode