# This is a workflow to compile MkDocs sources on *main* branch and update *docs-build* branch

name: Compile MkDocs source and update docs-build branch

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set Up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9.7
    - name: Update pip
      run: |
        pip install -U wheel
        pip install -U setuptools
        python -m pip install -U pip
    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"
    - name: Pip cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: MkDocs Link Check
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-verbose-mode: 'yes'
        folder-path: 'docs/'
    - name: Build MkDocs
      id: mkdocs-build
      run: |
        pip install -r requirements.txt
        mkdocs build
    - name: Add PHP index file
      run: |
        cd ./site/
        echo "<?php header( 'Location: /index.html' ) ;  ?>" > index.php
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        directory: 'site/'
        branch: docs-build
        force: true
